version: '3.8'

services:

  backend_face_app:
    build: .
    command: bash -c "/wait && alembic upgrade head && uvicorn backend.application:app --host 0.0.0.0"
    container_name: backend_face_app
    env_file:
      - .env-demo
    environment:
      - WAIT_HOSTS=face-app-postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - face-app-postgres
      - minio
    ports:
      - 8000:8000

  face-app-postgres:
    container_name: face-app-postgres
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env-demo
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=test
      - MINIO_SECRET_KEY=test1234
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data
    restart: unless-stopped

  minio_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 test test1234;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc policy set public myminio/images;
      exit 0;
      "

volumes:
  postgres_db:
    driver: local

  minio_storage:
    driver: local
